/*
    bit.h -- Build It Configuration Header for windows-x86

    This header is generated by Bit during configuration.
    You may edit this file, but Bit will overwrite it next
    time configuration is performed.
 */

/* Settings */
#define BIT__MINIMAL "doxygen,dsi,ejs,man,man2html,pmaker,ssl,matrixssl,openssl"
#define BIT_ACCESS_LOG 0
#define BIT_AUTH 1
#define BIT_BUILD_NUMBER "0"
#define BIT_CA_FILE ""
#define BIT_CA_PATH ""
#define BIT_CERTIFICATE ""
#define BIT_CGI 1
#define BIT_CGI_BIN "cgi-bin"
#define BIT_COMPANY "Embedthis"
#define BIT_DEBUG_LOG 1
#define BIT_DEPTH 1
#define BIT_DIGEST_AUTH 1
#define BIT_DOCUMENTS "web"
#define BIT_HAS_DYN_LOAD 1
#define BIT_HAS_LIB_EDIT 0
#define BIT_HAS_MMU 1
#define BIT_HAS_UNNAMED_UNIONS 1
#define BIT_HTTP_PORT 8080
#define BIT_HTTP_V6_PORT 9090
#define BIT_IF_MODIFIED 1
#define BIT_JAVASCRIPT 1
#define BIT_KEEP_ALIVE 1
#define BIT_KEY ""
#define BIT_LEGACY 0
#define BIT_LIMIT_BODY 8192
#define BIT_LIMIT_BUFFER 1024
#define BIT_LIMIT_FILENAME 256
#define BIT_LIMIT_HEADER 2048
#define BIT_LIMIT_HEADERS 4096
#define BIT_LIMIT_NUM_HEADERS 64
#define BIT_LIMIT_PASSWORD 32
#define BIT_LIMIT_RESPONSE_BUFFER 8192
#define BIT_LIMIT_SESSION_COUNT 120
#define BIT_LIMIT_SESSION_LIFE 1800
#define BIT_LIMIT_SOCKET_BUFFER 1024
#define BIT_LIMIT_STRING 4096
#define BIT_LIMIT_URL 2048
#define BIT_MINIMAL "doxygen,dsi,ejs,man,man2html,pmaker,matrixssl"
#define BIT_OPTIONAL "doxygen,dsi,ejs,man,man2html,openssl,matrixssl,pmaker,ssl,utest,zip"
#define BIT_PACKS "bits/packs"
#define BIT_PASSWORD ""
#define BIT_PRODUCT "goahead"
#define BIT_REPLACE_MALLOC 0
#define BIT_REQUIRED "winsdk,compiler,link,dumpbin,rc"
#define BIT_SESSIONS 1
#define BIT_SSL_PORT 4443
#define BIT_TITLE "Embedthis GoAhead"
#define BIT_TRACE "stdout:2"
#define BIT_VERSION "3.0.0"

/* Prefixes */
#define BIT_CFG_PREFIX "C:/Program Files (x86)/Embedthis GoAhead"
#define BIT_BIN_PREFIX "C:/Program Files (x86)/Embedthis GoAhead/bin"
#define BIT_INC_PREFIX "C:/Program Files (x86)/Embedthis GoAhead/inc"
#define BIT_LOG_PREFIX "C:/Program Files (x86)/Embedthis GoAhead/logs"
#define BIT_PRD_PREFIX "C:/Program Files (x86)/Embedthis GoAhead"
#define BIT_SPL_PREFIX "C:/Program Files (x86)/Embedthis GoAhead/tmp"
#define BIT_SRC_PREFIX "C:/Program Files (x86)/Embedthis GoAhead/src"
#define BIT_VER_PREFIX "C:/Program Files (x86)/Embedthis GoAhead"
#define BIT_WEB_PREFIX "C:/Program Files (x86)/Embedthis GoAhead/web"

/* Suffixes */
#define BIT_EXE ".exe"
#define BIT_SHLIB ".lib"
#define BIT_SHOBJ ".dll"
#define BIT_LIB ".a"
#define BIT_OBJ ".obj"

/* Profile */
#define BIT_GOAHEAD_PRODUCT 1
#define BIT_PROFILE "vs"
#define BIT_CONFIG_CMD "bit -d -q -platform windows-x86 -without all -profile vs -configure . -gen vs"

/* Miscellaneous */
#define BIT_MAJOR_VERSION 3
#define BIT_MINOR_VERSION 0
#define BIT_PATCH_VERSION 0
#define BIT_VNUM 300000000

/* Packs */
#define BIT_PACK_CC 1
#define BIT_PACK_DOXYGEN 0
#define BIT_PACK_DSI 0
#define BIT_PACK_DUMPBIN 0
#define BIT_PACK_EJS 0
#define BIT_PACK_LINK 1
#define BIT_PACK_MAN 0
#define BIT_PACK_MAN2HTML 0
#define BIT_PACK_MATRIXSSL 0
#define BIT_PACK_OPENSSL 0
#define BIT_PACK_PMAKER 0
#define BIT_PACK_RC 1
#define BIT_PACK_SSL 0
#define BIT_PACK_UTEST 1
#define BIT_PACK_WINSDK 1
#define BIT_PACK_ZIP 1
