/*
    bit.h -- Build It Configuration Header for macosx-x64

    This header is generated by Bit during configuration.
    You may edit this file, but Bit will overwrite it next
    time configuration is performed.
 */

/* Settings */
#define BIT__MINIMAL "doxygen,dsi,ejs,man,man2html,pmaker,ssl,matrixssl,openssl"
#define BIT_ACCESS_LOG 0
#define BIT_AUTH 1
#define BIT_BUILD_NUMBER "0"
#define BIT_CA_FILE ""
#define BIT_CA_PATH ""
#define BIT_CERTIFICATE ""
#define BIT_CGI 1
#define BIT_CGI_BIN "cgi-bin"
#define BIT_COMPANY "Embedthis"
#define BIT_DEBUG_LOG 1
#define BIT_DEPTH 1
#define BIT_DIGEST_AUTH 1
#define BIT_DOCUMENTS "web"
#define BIT_HAS_DOUBLE_BRACES 1
#define BIT_HAS_DYN_LOAD 1
#define BIT_HAS_LIB_EDIT 1
#define BIT_HAS_MMU 1
#define BIT_HAS_MTUNE 1
#define BIT_HAS_PAM 1
#define BIT_HAS_STACK_PROTECTOR 1
#define BIT_HAS_SYNC 1
#define BIT_HAS_SYNC_CAS 1
#define BIT_HAS_UNNAMED_UNIONS 1
#define BIT_HTTP_PORT 8080
#define BIT_HTTP_V6_PORT 9090
#define BIT_IF_MODIFIED 1
#define BIT_JAVASCRIPT 1
#define BIT_KEEP_ALIVE 1
#define BIT_KEY ""
#define BIT_LEGACY 0
#define BIT_LIMIT_BUFFER 1024
#define BIT_LIMIT_FILENAME 256
#define BIT_LIMIT_HEADER 2048
#define BIT_LIMIT_HEADERS 8192
#define BIT_LIMIT_PASSWORD 32
#define BIT_LIMIT_SESSION_COUNT 120
#define BIT_LIMIT_SESSION_LIFE 1800
#define BIT_LIMIT_SOCKET_BUFFER 512
#define BIT_LIMIT_STRING 4096
#define BIT_LIMIT_URL 2048
#define BIT_MINIMAL "doxygen,dsi,ejs,man,man2html,pmaker,matrixssl"
#define BIT_OPTIONAL "doxygen,dsi,ejs,man,man2html,openssl,matrixssl,pmaker,ssl,utest,zip"
#define BIT_PACKS "bits/packs"
#define BIT_PASSWORD ""
#define BIT_PRODUCT "goahead"
#define BIT_REPLACE_MALLOC 0
#define BIT_REQUIRED "compiler,link"
#define BIT_SESSIONS 1
#define BIT_SSL_PORT 4443
#define BIT_TITLE "Embedthis GoAhead"
#define BIT_TRACE "stdout:2"
#define BIT_VERSION "3.0.0"
#define BIT_WARN64TO32 1
#define BIT_WARN_UNUSED 1

/* Prefixes */
#define BIT_CFG_PREFIX "/etc/goahead"
#define BIT_BIN_PREFIX "/usr/lib/goahead/3.0.0/bin"
#define BIT_INC_PREFIX "/usr/lib/goahead/3.0.0/inc"
#define BIT_LOG_PREFIX "/var/log/goahead"
#define BIT_PRD_PREFIX "/usr/lib/goahead"
#define BIT_SPL_PREFIX "/var/spool/goahead"
#define BIT_SRC_PREFIX "/usr/src/goahead-3.0.0"
#define BIT_VER_PREFIX "/usr/lib/goahead/3.0.0"
#define BIT_WEB_PREFIX "/var/www/goahead-default"

/* Suffixes */
#define BIT_EXE ""
#define BIT_SHLIB ".dylib"
#define BIT_SHOBJ ".dylib"
#define BIT_LIB ".a"
#define BIT_OBJ ".o"

/* Profile */
#define BIT_GOAHEAD_PRODUCT 1
#define BIT_PROFILE "xcode"
#define BIT_CONFIG_CMD "bit -d -q -platform macosx-x64 -without all -profile xcode -configure . -gen xcode"

/* Miscellaneous */
#define BIT_MAJOR_VERSION 3
#define BIT_MINOR_VERSION 0
#define BIT_PATCH_VERSION 0
#define BIT_VNUM 300000000

/* Packs */
#define BIT_PACK_CC 1
#define BIT_PACK_DOXYGEN 0
#define BIT_PACK_DSI 0
#define BIT_PACK_EJS 0
#define BIT_PACK_LINK 1
#define BIT_PACK_MAN 0
#define BIT_PACK_MAN2HTML 0
#define BIT_PACK_MATRIXSSL 0
#define BIT_PACK_OPENSSL 1
#define BIT_PACK_PMAKER 0
#define BIT_PACK_SSL 1
#define BIT_PACK_UTEST 1
#define BIT_PACK_ZIP 1
