 
                    <a class="item" href="https://embedthis.com/">Embedthis</a>
                    <a class="item" href="https://embedthis.com/goahead/">GoAhead Site</a>
                    <span class="desktop-only">
                        <a class="item" href="http://goo.gl/9bL9rM">GoAhead News</a>
                        <a class="item" href="https://github.com/embedthis/goahead">Repository</a>
                        <a class="item" href="https://embedthis.com/blog/">Blog</a>
                        <a class="item" href="https://twitter.com/mobstream">Twitter</a>
                    </span>
