 
                    <a class="item" href="https://embedthis.com/">Embedthis</a>
                    <a class="item" href="https://embedthis.com/appweb/">Appweb Site</a>
                    <a class="item" href="http://goo.gl/dGRDl4">Appweb News</a>
                    <a class="item" href="https://github.com/embedthis/appweb">Repository</a>
                    <a class="item" href="https://embedthis.com/blog/">Blog</a>
                    <a class="item" href="https://twitter.com/mobstream">Twitter</a>
