
                    <a class="item" href="https://embedthis.com/">Embedthis</a>
                    <a class="item" href="https://embedthis.com/goahead/">GoAhead Site</a>
                    <span class="desktop-only">
                        <a class="item" href="https://embedthis.com/blog/categories/GoAhead/">GoAhead News</a>
                        <a class="item" href="https://github.com/embedthis/goahead">Repository</a>
                        <a class="item" href="https://embedthis.com/blog/">Blog</a>
                        <a class="item" href="https://twitter.com/embedthat">Twitter</a>
                    </span>
