<!DOCTYPE html>
<html lang="en">
<head>
    <title><@= meta.title @></title>
    <@ partial('head') @>
</head>
<body class="show-sidebar">
    <@ partial('sidebar') @>
    <div class="ui inverted masthead">
        <@ partial('nav') @>
    </div>
    <div class="content">
        <@ content @>
    </div>
    <@ partial('terms') @>
    <@ partial('scripts') @>
    <@ partial('reload') @>
</body>
</html>
