#!/bin/sh

echo "HTTP/1.0 200 OK"
echo "Content-type: text/html"
echo ""
echo "<html><body>"

cat big.txt big.txt big.txt big.txt big.txt big.txt big.txt
cat big.txt big.txt big.txt big.txt big.txt big.txt big.txt
cat big.txt big.txt big.txt big.txt big.txt big.txt big.txt
cat big.txt big.txt big.txt big.txt big.txt big.txt big.txt
cat big.txt big.txt big.txt big.txt big.txt big.txt big.txt
cat big.txt big.txt big.txt big.txt big.txt big.txt big.txt
cat big.txt big.txt big.txt big.txt big.txt big.txt big.txt
cat big.txt big.txt big.txt big.txt big.txt big.txt big.txt
cat big.txt big.txt big.txt big.txt big.txt big.txt big.txt
cat big.txt big.txt big.txt big.txt big.txt big.txt big.txt
cat big.txt big.txt big.txt big.txt big.txt big.txt big.txt
cat big.txt big.txt big.txt big.txt big.txt big.txt big.txt
cat big.txt big.txt big.txt big.txt big.txt big.txt big.txt
cat big.txt big.txt big.txt big.txt big.txt big.txt big.txt
cat big.txt big.txt big.txt big.txt big.txt big.txt big.txt
cat big.txt big.txt big.txt big.txt big.txt big.txt big.txt
cat big.txt big.txt big.txt big.txt big.txt big.txt big.txt
cat big.txt big.txt big.txt big.txt big.txt big.txt big.txt
cat big.txt big.txt big.txt big.txt big.txt big.txt big.txt
cat big.txt big.txt big.txt big.txt big.txt big.txt big.txt
cat big.txt big.txt big.txt big.txt big.txt big.txt big.txt
cat big.txt big.txt big.txt big.txt big.txt big.txt big.txt
cat big.txt big.txt big.txt big.txt big.txt big.txt big.txt
cat big.txt big.txt big.txt big.txt big.txt big.txt big.txt
cat big.txt big.txt big.txt big.txt big.txt big.txt big.txt
cat big.txt big.txt big.txt big.txt big.txt big.txt big.txt
cat big.txt big.txt big.txt big.txt big.txt big.txt big.txt
cat big.txt big.txt big.txt big.txt big.txt big.txt big.txt
cat big.txt big.txt big.txt big.txt big.txt big.txt big.txt
cat big.txt big.txt big.txt big.txt big.txt big.txt big.txt
cat big.txt big.txt big.txt big.txt big.txt big.txt big.txt
cat big.txt big.txt big.txt big.txt big.txt big.txt big.txt
cat big.txt big.txt big.txt big.txt big.txt big.txt big.txt
cat big.txt big.txt big.txt big.txt big.txt big.txt big.txt
cat big.txt big.txt big.txt big.txt big.txt big.txt big.txt
cat big.txt big.txt big.txt big.txt big.txt big.txt big.txt
cat big.txt big.txt big.txt big.txt big.txt big.txt big.txt
cat big.txt big.txt big.txt big.txt big.txt big.txt big.txt
cat big.txt big.txt big.txt big.txt big.txt big.txt big.txt
cat big.txt big.txt big.txt big.txt big.txt big.txt big.txt
cat big.txt big.txt big.txt big.txt big.txt big.txt big.txt
cat big.txt big.txt big.txt big.txt big.txt big.txt big.txt
cat big.txt big.txt big.txt big.txt big.txt big.txt big.txt
cat big.txt big.txt big.txt big.txt big.txt big.txt big.txt
cat big.txt big.txt big.txt big.txt big.txt big.txt big.txt
cat big.txt big.txt big.txt big.txt big.txt big.txt big.txt
cat big.txt big.txt big.txt big.txt big.txt big.txt big.txt
cat big.txt big.txt big.txt big.txt big.txt big.txt big.txt
cat big.txt big.txt big.txt big.txt big.txt big.txt big.txt
cat big.txt big.txt big.txt big.txt big.txt big.txt big.txt
cat big.txt big.txt big.txt big.txt big.txt big.txt big.txt
cat big.txt big.txt big.txt big.txt big.txt big.txt big.txt
cat big.txt big.txt big.txt big.txt big.txt big.txt big.txt
cat big.txt big.txt big.txt big.txt big.txt big.txt big.txt
cat big.txt big.txt big.txt big.txt big.txt big.txt big.txt
cat big.txt big.txt big.txt big.txt big.txt big.txt big.txt
cat big.txt big.txt big.txt big.txt big.txt big.txt big.txt
cat big.txt big.txt big.txt big.txt big.txt big.txt big.txt
cat big.txt big.txt big.txt big.txt big.txt big.txt big.txt
cat big.txt big.txt big.txt big.txt big.txt big.txt big.txt
cat big.txt big.txt big.txt big.txt big.txt big.txt big.txt
cat big.txt big.txt big.txt big.txt big.txt big.txt big.txt
cat big.txt big.txt big.txt big.txt big.txt big.txt big.txt
cat big.txt big.txt big.txt big.txt big.txt big.txt big.txt
cat big.txt big.txt big.txt big.txt big.txt big.txt big.txt
cat big.txt big.txt big.txt big.txt big.txt big.txt big.txt
cat big.txt big.txt big.txt big.txt big.txt big.txt big.txt
cat big.txt big.txt big.txt big.txt big.txt big.txt big.txt
cat big.txt big.txt big.txt big.txt big.txt big.txt big.txt
cat big.txt big.txt big.txt big.txt big.txt big.txt big.txt
cat big.txt big.txt big.txt big.txt big.txt big.txt big.txt
cat big.txt big.txt big.txt big.txt big.txt big.txt big.txt
cat big.txt big.txt big.txt big.txt big.txt big.txt big.txt
cat big.txt big.txt big.txt big.txt big.txt big.txt big.txt
cat big.txt big.txt big.txt big.txt big.txt big.txt big.txt
cat big.txt big.txt big.txt big.txt big.txt big.txt big.txt
cat big.txt big.txt big.txt big.txt big.txt big.txt big.txt
cat big.txt big.txt big.txt big.txt big.txt big.txt big.txt
cat big.txt big.txt big.txt big.txt big.txt big.txt big.txt
cat big.txt big.txt big.txt big.txt big.txt big.txt big.txt
cat big.txt big.txt big.txt big.txt big.txt big.txt big.txt
cat big.txt big.txt big.txt big.txt big.txt big.txt big.txt
cat big.txt big.txt big.txt big.txt big.txt big.txt big.txt
cat big.txt big.txt big.txt big.txt big.txt big.txt big.txt
cat big.txt big.txt big.txt big.txt big.txt big.txt big.txt
cat big.txt big.txt big.txt big.txt big.txt big.txt big.txt
cat big.txt big.txt big.txt big.txt big.txt big.txt big.txt
cat big.txt big.txt big.txt big.txt big.txt big.txt big.txt
cat big.txt big.txt big.txt big.txt big.txt big.txt big.txt
cat big.txt big.txt big.txt big.txt big.txt big.txt big.txt
cat big.txt big.txt big.txt big.txt big.txt big.txt big.txt
cat big.txt big.txt big.txt big.txt big.txt big.txt big.txt
cat big.txt big.txt big.txt big.txt big.txt big.txt big.txt
cat big.txt big.txt big.txt big.txt big.txt big.txt big.txt
cat big.txt big.txt big.txt big.txt big.txt big.txt big.txt
cat big.txt big.txt big.txt big.txt big.txt big.txt big.txt
echo "</body></html>"
