<!DOCTYPE html>
<html lang="en">
<head>
    <title><%= meta.title %></title>
    <% partial('head') %>
</head>
<body>
    <% partial('sidebar') %>
    <div class="ui inverted masthead">
        <% partial('nav') %>
    </div>
    <div class="content">
        <% content %>
    </div>
    <% partial('terms') %>
    <script src="@@{top}lib/jquery/jquery.js"></script>
    <script src="@@{top}lib/semantic/packaged/javascript/semantic.js"></script>
    <script>
        $('.sidebar').sidebar({overlay: false}).sidebar('toggle');
        $('.sidebar').first().sidebar('attach events', '.toggle.button');
    </script>
</body>
</html>
